### ISSUE TITLE
Not working under NodeJS 0.12.0

### ISSUE THREAD

**Issue by user3160** [elliotttf/img64#4]
I get the following error when running under NodeJs 0.12.0:

  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )

The problem is solved if I set the jsdom dependency in package.json to "latest". Current jsdom version is 3.1.1 while the package.json has ~0.3.0. Please update the reference to jsdom, thanks!

**Comment by elliotttf** [comment]
:+1: thanks for the report. I have this fixed locally, just dealing with some failing tests. I will hopefully have an update published tomorrow.

**Comment by elliotttf** [comment]
Closed by 096918f
